version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: collectoros-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: collectoros_db
    ports:
      - "5432:5432"
    volumes:
      - collectoros_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: collectoros-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  collectoros_postgres_data: